const theme = {
	colors: {
		primaryColor: '#ffffff',
		themeOpositeColor: '#ffff',
		background: '#ffffff',
		footerBackground: '#ffffff',
		explorerBackground: '#ffffff',
		footerTextColor: '#ffffff',
		sideBar: '#0a0b0d',
		menuActiveBackground: '#ffffff',
		white: '#fff',
		black: '#ffffff',
		nodeInactiveColor: '#ffffff',
		descriptionTextColor: '#ffffff',
		settingBlockColor: '#ffffff',
		borderColor: '#ffffff',
		buttonWhiteColor: '#ffffff',
		buttonRedColor: '#ffffff',
		buttonGreenColor: '#ffffff',
		inputBackgroundColor: '#ffffff',
		inputTextColor: '#ffffff',
		tagCancelColor: '#ffffff',
		tagSuccessColor: '#ffffff',
		tagInfoColor: '#ffffff',
		tagWarningColor: '#ffffff',
		tableColumnColor: '#ffffff',
		tableColumnHoverColor: '#15171beb',
		tableActivePagination: '#0a0b0d',
		tabCardNavColor: '#ffffff',
		hrColor: '#ffffff',
		helpTextColor: '#ffffff',
		helpSideBarColor: '#111215',
		helpTableBorderColor: '#ffffff',
		helpTableRowLightColor: '#ffffff',
		helpTableRowDarkColor: '#ffffff',
		authModalTextColor: '#ffffff',
		dropdownOptionsColor: '#ffffff',
		dropdownBackgroundColor: '#ffffff',
		bankingAssetsStatusColor: '#ffffff',
		bankingAssetsDetailBackground: '#ffffff',
	},
	sizes: {
		lg: '992px',
		sm: '576px',
	},
};

export default theme;
