const theme = {
	colors: {
		primaryColor: '#ffc000',
		themeOpositeColor: '#000000',
		background: '#ffffff',
		footerBackground: '#aaaaaa',
		explorerBackground: '#aaaaaa',
		footerTextColor: '#ffffff',
		sideBar: '#ffffff',
		menuActiveBackground: '#ffc000',
		white: '#fff',
		black: '#ffffff',
		nodeInactiveColor: '#ffffff',
		descriptionTextColor: '#ffffff',
		settingBlockColor: '#aaaaaa',
		borderColor: '#eaeaea',
		buttonWhiteColor: '#000000',
		buttonRedColor: '#ff2929',
		buttonGreenColor: '#0f923a',
		inputBackgroundColor: '#aaaaaa',
		inputTextColor: '#ffffff',
		inputBorderColor: '#eaeaea',
		tagCancelColor: '#ffffff',
		tagSuccessColor: '#ffffff',
		tagInfoColor: '#ffffff',
		tagWarningColor: '#ffffff',
		tableColumnColor: '#ffffff',
		tableColumnHoverColor: '#aaaaaa',
		tableActivePagination: '#0a0b0d',
		tabCardNavColor: '#ffffff',
		hrColor: '#ffffff',
		helpTextColor: '#ffffff',
		helpSideBarColor: '#111215',
		helpTableBorderColor: '#ffffff',
		helpTableRowLightColor: '#ffffff',
		helpTableRowDarkColor: '#ffffff',
		authModalTextColor: '#ffffff',
		dropdownOptionsColor: '#ffffff',
		dropdownBackgroundColor: '#ffffff',
		bankingAssetsStatusColor: '#ffffff',
		bankingAssetsDetailBackground: '#ffffff',
		bidRowBackgroundColor: '#d9f8f0',
		askRowBackgroundColor: '#ffeaec',
		orderTextColor: '#666666',
		assetSymbolColor: '#000000',
	},
	sizes: {
		lg: '992px',
		sm: '576px',
	},
};

export default theme;
