version: "2"
volumes:
    wallet_build: {}

services:
    web-wallet:
        build: .
        ports:
            - "8080:80"
        volumes:
            - wallet_build:/meta-ui/build/dist
            - .:/meta-ui
